##############################
#
# Web-Application - Image
# Based on Payara-full-Image
#
##############################

FROM hackathon-ubuntu-16.04-java-8-jdk-payara-4.1.1

MAINTAINER Ken Brucksch <ken.brucksch@fntsoftware.com>

# Copy webapp
COPY dev-obst-billing-1.0.0-SNAPSHOT.war /webapps/

# Start Service and deploy application
CMD ./start-payara-service.sh
