##################################################
#
# Compose-File for start up payara-4-full
# application server with database connection pool,
# using a postgresql conainer with postgres
# default image from dockerhub.
#
##################################################

version: "2"

services:

    postgres-for-catalog:
        image: postgres:9.6
        container_name: postgres-for-catalog
        environment:
            - POSTGRES_USER=devobst_catalog
            - POSTGRES_PASSWORD=devobst_catalog
        networks:
            - net
        ports:
            - "5432:5432"
        volumes:
            - postgres_data_catalog:/var/lib/postgresql/data
        depends_on:
            - devobst-openmq

    devobst-openmq:
        image: hackathon-ubuntu-16.04-java-8-jdk-openmq-5.1.1
        container_name: devobst-openmq
        environment:
            - TOPIC_NAME=devobst
        networks:
            - net
        ports:
            - "7676:7676"
            - "31000:31000"
            - "34000:34000"
            - "36000:36000"
            - "43000:43000"
        volumes:
            - openmq_data:/opt/openmq/MessageQueue5.1.1/var/mq/instances/imqbroker
                    
    devobst-catalog:
        image: hackathon-ubuntu-16.04-java-8-jdk-payara-4.1.1-app
        container_name: devobst-catalog
        environment:
            - ADMIN_USER=admin
            - ADMIN_PASSWORD=password
            - DB_USER=devobst_catalog
            - DB_PASSWORD=devobst_catalog
            - DB_SERVER_NAME=postgres-for-catalog
            - DB_PORT=5432
            - DB_NAME=devobst_catalog
            - CONNECTION_POOLNAME=devobst_catalog
            - CONNECTION_RESOURCE_NAME=jdbc/devobst-catalog
            - MQHOST=devobst-openmq
            - MQPORT=7676
        networks:
            - net
        ports:
            - "8080:8080"
            - "4848:4848"
            - "9009:9009"
        depends_on:
            - postgres-for-catalog

networks:
    net:

volumes:
    postgres_data_catalog:
    openmq_data:
